"""One-off content script: adds the playlist clubs that sit in the top five
leagues plus MLS, each with a verified Spotify track.

Chant layers carry the chant's name and our own explanation of what it means —
never the lyric itself.
"""

import io
import json
import os
from collections import Counter

ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
PL = 'league-premier-league'
L1 = 'league-ligue-1'


def sp(track_id):
    return f'https://open.spotify.com/track/{track_id}'


def card(cid, league, order, club, city, founded, colors, nick, nick_lit, nick_mean,
         summary, stadium, traditions, rivalry, chant, club_es=None):
    return {
        'id': cid,
        'leagueId': league,
        'order': order,
        'club': {'en': club} if club_es is None else {'en': club, 'es': club_es},
        'city': {'en': city[0], 'es': city[1]},
        'founded': founded,
        'colors': {'en': colors[0], 'es': colors[1]},
        'nickname': {
            'original': {'text': nick[0], 'lang': nick[1]},
            'literal': {'en': nick_lit[0], 'es': nick_lit[1]},
            'meaning': {'en': nick_mean[0], 'es': nick_mean[1]},
        },
        'summary': {'en': summary[0], 'es': summary[1]},
        'stadium': {
            'name': {'en': stadium},
            'traditions': [{'en': t[0], 'es': t[1]} for t in traditions],
        },
        'rivalries': [{
            'name': {'en': rivalry[0], 'es': rivalry[1]},
            'opponent': {'en': rivalry[2]} if rivalry[3] is None else {'en': rivalry[2], 'es': rivalry[3]},
            'opponentCultureId': rivalry[4],
            'description': {'en': rivalry[5], 'es': rivalry[6]},
        }],
        'chants': [{
            'id': chant[0],
            'title': {'en': chant[1], 'es': chant[2]},
            'when': {'en': chant[3], 'es': chant[4]},
            'sourceUrl': None,
            'spotifyUrl': sp(chant[5]),
            'original': {'text': chant[6], 'lang': chant[7]},
            'literal': {'en': chant[8], 'es': chant[9]},
            'meaning': {'en': chant[10], 'es': chant[11]},
        }],
        'contentStatus': 'draft',
    }


NEW = [
    card('culture-manchester-city', PL, 4, 'Manchester City',
         ('Manchester, England', 'Mánchester, Inglaterra'), 1880, ('Sky blue', 'Azul cielo'),
         ('The Citizens', 'en'), ('The Citizens', 'Los Ciudadanos'),
         ("Shortened by fans to 'City'. The club began as a church team in east Manchester and took the city's name as its own.",
          "Los aficionados lo abrevian a 'City'. El club nació como equipo de una parroquia del este de Mánchester y tomó el nombre de la ciudad."),
         ("Decades of near-misses and relegations turned into sustained dominance after 2008 — a change the older songs still remember.",
          "Décadas de fracasos por poco y descensos se convirtieron en dominio sostenido tras 2008, un cambio que los cánticos antiguos aún recuerdan."),
         'Etihad Stadium',
         [("Built for the 2002 Commonwealth Games and taken over by the club in 2003, after nearly 80 years at Maine Road.",
           "Construido para los Juegos de la Commonwealth de 2002 y ocupado por el club en 2003, tras casi 80 años en Maine Road."),
          ("Fans sing about the lean years as loudly as the trophies — the identity was built before the money arrived.",
           "La afición canta sobre los años malos tan alto como sobre los títulos: la identidad se construyó antes de que llegara el dinero.")],
         ('Manchester Derby', 'Derbi de Mánchester', 'Manchester United', None, 'culture-manchester-united',
          "One city, two clubs, and a rivalry that flipped as City rose.",
          "Una ciudad, dos clubes y una rivalidad que se dio la vuelta con el ascenso del City."),
         ('blue-moon', 'Blue Moon', 'Blue Moon',
          'Before kickoff and through the hard moments', 'Antes del saque inicial y en los momentos difíciles',
          '3o0lr4KlzgCcQz7iatgFNB', 'Blue Moon', 'en', 'Blue Moon', 'Luna azul',
          "A wistful 1930s standard, adopted because a song about loneliness fitted a club that spent years in the shadows. It is sung in celebration now — the joke being that the melancholy never quite left.",
          "Un clásico melancólico de los años 30, adoptado porque una canción sobre la soledad encajaba con un club que pasó años a la sombra. Hoy se canta celebrando, con la broma de que la melancolía nunca se fue del todo.")),

    card('culture-chelsea', PL, 5, 'Chelsea',
         ('London, England', 'Londres, Inglaterra'), 1905, ('Royal blue', 'Azul rey'),
         ('The Pensioners', 'en'), ('The Pensioners', 'Los Pensionistas'),
         ("The club's first badge showed a Chelsea Pensioner — an army veteran of the Royal Hospital Chelsea, whose scarlet coats are a local sight. 'The Blues' is the everyday name now.",
          "El primer escudo del club mostraba a un 'Chelsea Pensioner', veterano del Royal Hospital Chelsea, cuyos abrigos escarlata son una estampa del barrio. Hoy se les llama simplemente 'The Blues'."),
         ("A west London club that went from cult status to serial winner, with a support built around one famously noisy end of the ground.",
          "Un club del oeste de Londres que pasó de equipo de culto a ganador en serie, con una afición construida en torno a una grada famosa por su ruido."),
         'Stamford Bridge',
         [("The Shed End, once a covered terrace, gave the loudest supporters their name and still houses them.",
           "El Shed End, antaño una grada cubierta, dio nombre a los aficionados más ruidosos y sigue siendo su hogar."),
          ("One of the oldest grounds in London still in use, hemmed in by streets on every side.",
           "Uno de los estadios más antiguos de Londres aún en uso, encajonado por calles en todos sus lados.")],
         ('London derby', 'Derbi londinense', 'Tottenham Hotspur', None, 'culture-tottenham',
          "One of several London rivalries Chelsea carry; this is the one with the most needle in recent years.",
          "Una de las varias rivalidades londinenses del Chelsea; la más tensa en los últimos años."),
         ('ten-men-went-to-mow', '10 Men Went To Mow', '10 Men Went To Mow',
          'Counted out slowly across the second half', 'Se cuenta despacio durante la segunda parte',
          '3zL7H4sGdE5r0pC5jq5Krw', '10 Men Went To Mow', 'en', 'Ten men went to mow', 'Diez hombres fueron a segar',
          "A children's counting song turned terrace ritual: the number climbs one at a time, so the whole stand has to stay with it for several minutes. Endurance is the point, not the words.",
          "Una canción infantil de contar convertida en ritual de grada: el número sube de uno en uno, así que toda la tribuna debe seguirla varios minutos. Lo importante es aguantar, no la letra.")),

    card('culture-tottenham', PL, 6, 'Tottenham Hotspur',
         ('London, England', 'Londres, Inglaterra'), 1882, ('White and navy', 'Blanco y azul marino'),
         ('The Lilywhites', 'en'), ('The Lilywhites', 'Los Blanquilirios'),
         ("For the plain white shirts. The cockerel on the badge wears spurs, after Harry Hotspur, the medieval nobleman the club is named for.",
          "Por las camisetas blancas lisas. El gallo del escudo lleva espuelas, en referencia a Harry Hotspur, el noble medieval que da nombre al club."),
         ("A club that measures itself by how it plays as much as by what it wins, with one of the most modern stadiums in Europe.",
          "Un club que se mide tanto por cómo juega como por lo que gana, con uno de los estadios más modernos de Europa."),
         'Tottenham Hotspur Stadium',
         [("Opened in 2019 with a retractable pitch: the grass surface slides away to reveal an artificial one underneath.",
           "Inaugurado en 2019 con césped retráctil: la superficie de hierba se desliza y deja al descubierto otra artificial debajo."),
          ("The single-tier South Stand holds around 17,500 and was designed to concentrate the noise.",
           "La grada sur de un solo anillo acoge a unos 17.500 aficionados y se diseñó para concentrar el ruido.")],
         ('North London Derby', 'Derbi del Norte de Londres', 'Arsenal', None, 'culture-arsenal',
          "The rivalry that defines the club's calendar, with neighbours barely four miles away.",
          "La rivalidad que define el calendario del club, con unos vecinos a apenas seis kilómetros."),
         ('spurs-go-marching-in', 'Oh When The Spurs Go Marching In', 'Oh When The Spurs Go Marching In',
          'When the team is on top', 'Cuando el equipo domina',
          '2mXRXF67mvvpDMJ7JoRLUe', 'Oh when the Spurs go marching in', 'en',
          'Oh, when the Spurs go marching in', 'Oh, cuando el Tottenham entre desfilando',
          "Built on an old gospel marching tune that clubs around the world have borrowed — you'll hear the same melody with a different name in half a dozen stadiums.",
          "Se apoya en una vieja melodía de marcha góspel que clubes de todo el mundo han tomado prestada: oirás la misma música con otro nombre en media docena de estadios.")),

    card('culture-west-ham', PL, 7, 'West Ham United',
         ('London, England', 'Londres, Inglaterra'), 1895, ('Claret and blue', 'Granate y azul'),
         ('The Irons', 'en'), ('The Irons', 'Los Herreros'),
         ("The club began as the works team of Thames Ironworks, a shipbuilder on the river. The crossed hammers on the badge are riveting hammers from the yard, not weapons.",
          "El club nació como equipo de la fábrica Thames Ironworks, un astillero junto al río. Los martillos cruzados del escudo son martillos de remachar, no armas."),
         ("A working-class east London club whose identity is tied to the docks that built it, and to a song about something beautiful that bursts.",
          "Un club obrero del este de Londres cuya identidad está ligada a los muelles que lo levantaron y a una canción sobre algo bello que estalla."),
         'London Stadium',
         [("Bubble machines fill the air before kickoff, matching the club's anthem.",
           "Las máquinas de burbujas llenan el aire antes del saque inicial, a juego con el himno del club."),
          ("The club moved in 2016 from the Boleyn Ground, its home for 112 years — a move many supporters still argue about.",
           "El club se mudó en 2016 desde el Boleyn Ground, su casa durante 112 años, un traslado que muchos aficionados aún discuten.")],
         ('Dockers derby', 'Derbi de los estibadores', 'Millwall', None, None,
          "A rivalry rooted in competing dockyards on opposite banks of the Thames, rarely played now that the clubs sit in different divisions.",
          "Una rivalidad nacida de astilleros rivales en orillas opuestas del Támesis, hoy poco frecuente porque los clubes están en divisiones distintas."),
         ('forever-blowing-bubbles', "I'm Forever Blowing Bubbles", "I'm Forever Blowing Bubbles",
          'Before kickoff, with the bubble machines running', 'Antes del saque inicial, con las máquinas de burbujas en marcha',
          '6aFF1AgzYRpDDMCjdqybrT', "I'm Forever Blowing Bubbles", 'en',
          "I'm forever blowing bubbles", 'Siempre estoy soplando burbujas',
          "A music-hall song from 1918 about bubbles that rise beautifully and then burst, which supporters adopted — with some self-awareness — as a description of following this club.",
          "Una canción de music-hall de 1918 sobre burbujas que suben preciosas y luego estallan, que la afición adoptó, con cierta autoconciencia, como descripción de lo que es seguir a este club.")),

    card('culture-newcastle', PL, 8, 'Newcastle United',
         ('Newcastle upon Tyne, England', 'Newcastle upon Tyne, Inglaterra'), 1892,
         ('Black and white stripes', 'Rayas blancas y negras'),
         ('The Toon', 'en'), ('The Town', 'La Ciudad'),
         ("'Toon' is how 'town' sounds in the Geordie dialect of north-east England. Calling the club 'the Toon' makes it the town itself, not a team in it.",
          "'Toon' es como suena 'town' (ciudad) en el dialecto geordie del noreste de Inglaterra. Llamar al club 'the Toon' lo convierte en la ciudad misma, no en un equipo de ella."),
         ("One of the largest and most loyal followings in England, sustained through decades without a major trophy.",
          "Una de las aficiones más numerosas y leales de Inglaterra, mantenida durante décadas sin un gran título."),
         "St James' Park",
         [("The ground sits in the middle of the city centre, so matchday crowds fill the surrounding streets rather than a car park.",
           "El estadio está en pleno centro de la ciudad, así que la gente llena las calles de alrededor en vez de un aparcamiento."),
          ("The Gallowgate End holds the most vocal support, and half the city wears the stripes on matchday.",
           "El Gallowgate End reúne a los más ruidosos, y media ciudad viste las rayas el día del partido.")],
         ('Tyne–Wear Derby', 'Derbi del Tyne y el Wear', 'Sunderland', None, 'culture-sunderland',
          "Twelve miles apart on the north-east coast, and the most keenly felt fixture in the region.",
          "A veinte kilómetros de distancia en la costa noreste, y el partido que más se siente en la región."),
         ('blaydon-races', 'Blaydon Races', 'Blaydon Races',
          'Throughout the match', 'Durante todo el partido',
          '2Yl6ohsNyqdqTapTixsHay', 'Blaydon Races', 'en', 'Blaydon Races', 'Las carreras de Blaydon',
          "A Tyneside folk song from 1862 about a chaotic trip to a local race meeting. It is a regional anthem first and a football song second — which is exactly the point on Tyneside.",
          "Una canción popular del Tyneside de 1862 sobre un viaje caótico a unas carreras locales. Es antes un himno regional que un cántico de fútbol, y eso es justo lo que importa en Tyneside.")),

    card('culture-sunderland', PL, 9, 'Sunderland',
         ('Sunderland, England', 'Sunderland, Inglaterra'), 1879,
         ('Red and white stripes', 'Rayas rojas y blancas'),
         ('The Black Cats', 'en'), ('The Black Cats', 'Los Gatos Negros'),
         ("Chosen by a supporters' vote in 1997, reviving a much older local story: a gun battery on the River Wear was known as the Black Cat.",
          "Elegido por votación de la afición en 1997, recuperando una historia local mucho más antigua: una batería de cañones en el río Wear se conocía como el Gato Negro."),
         ("A club whose ground is a memorial to the coal industry that built the city, and whose support turns up in numbers regardless of the division.",
          "Un club cuyo estadio es un homenaje a la industria del carbón que levantó la ciudad, y cuya afición acude en masa sin importar la división."),
         'Stadium of Light',
         [("Built on the site of the Monkwearmouth colliery; a giant Davy miner's lamp stands outside the entrance.",
           "Construido sobre el terreno de la mina de Monkwearmouth; una lámpara de minero Davy gigante se alza en la entrada."),
          ("The name honours the lamps carried underground, not the football — a memorial to the men who worked there.",
           "El nombre honra las lámparas que se llevaban bajo tierra, no al fútbol: es un homenaje a los hombres que trabajaron allí.")],
         ('Tyne–Wear Derby', 'Derbi del Tyne y el Wear', 'Newcastle United', None, 'culture-newcastle',
          "The north-east derby, between two cities that share an industry and almost nothing else on matchday.",
          "El derbi del noreste, entre dos ciudades que comparten una industria y casi nada más el día del partido."),
         ('wise-men-say', 'Wise Men Say', 'Wise Men Say',
          'Before kickoff', 'Antes del saque inicial',
          '18XmPX6lfAfHlLw1HrMB4e', 'Wise Men Say', 'en', 'Wise men say', 'Los sabios dicen',
          "Adapted from a 1961 ballad and sung slowly by the whole ground before kickoff. The tempo is the tradition: it is closer to a hymn than a chant.",
          "Adaptada de una balada de 1961 y cantada despacio por todo el estadio antes del saque inicial. El ritmo es la tradición: se parece más a un himno que a un cántico.")),

    card('culture-brighton', PL, 10, 'Brighton & Hove Albion',
         ('Brighton, England', 'Brighton, Inglaterra'), 1901,
         ('Blue and white stripes', 'Rayas azules y blancas'),
         ('The Seagulls', 'en'), ('The Seagulls', 'Las Gaviotas'),
         ("Invented on the terraces in the 1970s as an answer to Crystal Palace fans chanting 'Eagles' — the seaside crowd shouted back the bird they actually had. The club adopted it afterwards.",
          "Nació en la grada en los años 70 como respuesta a los aficionados del Crystal Palace que cantaban '¡Águilas!': la afición costera les devolvió el pájaro que sí tenían. El club lo adoptó después."),
         ("A club that nearly disappeared in the 1990s after losing its ground, and returned to the top flight two decades later.",
          "Un club que estuvo a punto de desaparecer en los 90 tras perder su estadio y volvió a la élite dos décadas después."),
         'American Express Stadium',
         [("The club spent years without a home of its own, including a spell playing at an athletics track, before this ground opened in 2011.",
           "El club pasó años sin estadio propio, incluida una etapa jugando en una pista de atletismo, antes de que este se inaugurara en 2011."),
          ("The nickname chant is call-and-response: one side of the ground starts it, the other answers.",
           "El cántico del apodo es de llamada y respuesta: un lado del estadio lo empieza y el otro contesta.")],
         ('M23 Derby', 'Derbi de la M23', 'Crystal Palace', None, 'culture-crystal-palace',
          "Named after the motorway connecting the two clubs, and far fiercer than the 45-mile distance suggests.",
          "Debe su nombre a la autopista que une a los dos clubes, y es mucho más feroz de lo que sugieren sus 70 km de distancia."),
         ('sussex-by-the-sea', "Good Ol' Sussex By The Sea", "Good Ol' Sussex By The Sea",
          'Before kickoff', 'Antes del saque inicial',
          '7FAngmfg5bbcq68xboZePB', 'Sussex by the Sea', 'en', 'Sussex by the sea', 'Sussex junto al mar',
          "The county song of Sussex, older than the club and sung at local events far beyond football. Choosing it makes the team stand for the whole county, not just the town.",
          "La canción del condado de Sussex, más antigua que el club y cantada en actos locales mucho más allá del fútbol. Elegirla hace que el equipo represente a todo el condado, no solo a la ciudad.")),

    card('culture-nottingham-forest', PL, 11, 'Nottingham Forest',
         ('Nottingham, England', 'Nottingham, Inglaterra'), 1865, ('Garibaldi red', 'Rojo garibaldino'),
         ('The Tricky Trees', 'en'), ('The Tricky Trees', 'Los Árboles Escurridizos'),
         ("A play on the tree on the club badge. The red shirts honour Giuseppe Garibaldi's redshirts, adopted in 1865.",
          "Un juego con el árbol del escudo. Las camisetas rojas homenajean a los camisas rojas de Giuseppe Garibaldi, adoptadas en 1865."),
         ("One of the oldest clubs in the world, and the unlikeliest European champion: back-to-back European Cups in 1979 and 1980.",
          "Uno de los clubes más antiguos del mundo y el campeón europeo más improbable: dos Copas de Europa consecutivas en 1979 y 1980."),
         'The City Ground',
         [("The ground sits on the bank of the River Trent; Notts County's stadium is a few hundred metres away on the opposite side.",
           "El estadio está a la orilla del río Trent; el del Notts County está a unos cientos de metros en la orilla opuesta."),
          ("Two European Cups sit in the trophy room of a club from a city of around 320,000 people.",
           "Dos Copas de Europa descansan en la sala de trofeos de un club de una ciudad de unos 320.000 habitantes.")],
         ('East Midlands Derby', 'Derbi de East Midlands', 'Derby County', None, None,
          "A bitter regional rivalry, sharpened by the manager who left one club and won Europe with the other.",
          "Una agria rivalidad regional, agudizada por el entrenador que dejó un club y ganó Europa con el otro."),
         ('city-ground', 'City Ground', 'City Ground',
          'Throughout the match', 'Durante todo el partido',
          '1GHqjB3kpE7SsX70ks9ctL', 'City Ground', 'en', 'City Ground', 'City Ground',
          "Named for the stadium itself. Forest songs lean on place and history rather than players, because the history is the selling point.",
          "Lleva el nombre del propio estadio. Los cánticos del Forest se apoyan en el lugar y la historia más que en los jugadores, porque la historia es el argumento.")),

    card('culture-crystal-palace', PL, 12, 'Crystal Palace',
         ('London, England', 'Londres, Inglaterra'), 1905, ('Red and blue stripes', 'Rayas rojas y azules'),
         ('The Eagles', 'en'), ('The Eagles', 'Las Águilas'),
         ("Adopted in the 1970s. Before that the club were 'the Glaziers', after the glassworkers of the Crystal Palace, the vast glass exhibition hall the club is named for.",
          "Adoptado en los años 70. Antes el club era 'los Vidrieros', por los obreros del vidrio del Crystal Palace, el enorme palacio de cristal que da nombre al club."),
         ("A south London club with a supporters' section that imports its style from continental ultras — drums, flags and constant noise.",
          "Un club del sur de Londres con una grada que importa su estilo de los ultras continentales: tambores, banderas y ruido constante."),
         'Selhurst Park',
         [("The Holmesdale Road End runs ultras-style support: a capo facing the crowd, drums, and full-stand flag displays.",
           "El Holmesdale Road End funciona al estilo ultra: un capo de cara a la grada, tambores y despliegues de banderas en toda la tribuna."),
          ("Visiting players regularly name it the loudest ground they play at in England.",
           "Los jugadores visitantes lo señalan a menudo como el estadio más ruidoso en el que juegan en Inglaterra.")],
         ('M23 Derby', 'Derbi de la M23', 'Brighton & Hove Albion', None, 'culture-brighton',
          "London against the coast, and the fixture both sets of supporters look for first.",
          "Londres contra la costa, y el partido que ambas aficiones buscan primero en el calendario."),
         ('glad-all-over', 'Glad All Over', 'Glad All Over',
          'After a goal', 'Tras un gol',
          '2mF0iPGOhKfen06iiGf996', 'Glad All Over', 'en', 'Glad all over', 'Contento del todo',
          "A 1960s pop hit adopted in the same decade, with the crowd stamping on the beat. The stand physically shakes, which is half the reason it stuck.",
          "Un éxito pop de los años 60 adoptado en esa misma década, con la grada pateando a ritmo. La tribuna tiembla de verdad, y esa es media razón de que se quedara.")),

    card('culture-leeds', PL, 13, 'Leeds United',
         ('Leeds, England', 'Leeds, Inglaterra'), 1919, ('All white', 'Todo blanco'),
         ('The Whites', 'en'), ('The Whites', 'Los Blancos'),
         ("The all-white kit was adopted in the 1960s in deliberate imitation of Real Madrid. Fans also use 'the Peacocks', after the pub beside the ground.",
          "La equipación toda blanca se adoptó en los años 60 imitando deliberadamente al Real Madrid. La afición también usa 'los Pavos Reales', por el pub junto al estadio."),
         ("A one-club city with a famously uncompromising support, formed in 1919 after its predecessor was wound up.",
          "Una ciudad de un solo club con una afición famosa por su intransigencia, fundada en 1919 tras la disolución de su predecesor."),
         'Elland Road',
         [("The South Stand's noise is a tradition in itself; visiting teams are warned about it.",
           "El ruido de la grada sur es una tradición en sí misma; se avisa a los equipos visitantes."),
          ("The club's anthem is sung before kickoff by the whole ground, in the divisions above and below alike.",
           "Todo el estadio canta el himno del club antes del saque inicial, tanto en las divisiones de arriba como en las de abajo.")],
         ('Roses Rivalry', 'Rivalidad de las Rosas', 'Manchester United', None, 'culture-manchester-united',
          "Yorkshire against Lancashire — a rivalry borrowed from a 15th-century civil war and taken entirely seriously.",
          "Yorkshire contra Lancashire: una rivalidad heredada de una guerra civil del siglo XV y tomada completamente en serio."),
         ('marching-on-together', 'Marching On Together', 'Marching On Together',
          'Before kickoff', 'Antes del saque inicial',
          '7I7hWrtgfwOTn1A7Kufw09', 'Marching On Together', 'en',
          'Marching on together', 'Marchando juntos',
          "Recorded for a 1972 cup final and originally the B-side — the fans preferred it to the A-side and made it the anthem. It has outlasted every team that has played under it.",
          "Grabada para una final de copa en 1972 y originalmente la cara B: la afición la prefirió a la cara A y la convirtió en himno. Ha sobrevivido a todos los equipos que han jugado bajo ella.")),

    card('culture-psg', L1, 1, 'Paris Saint-Germain',
         ('Paris, France', 'París, Francia'), 1970, ('Blue, red and white', 'Azul, rojo y blanco'),
         ('Les Rouge-et-Bleu', 'fr'), ('The Red-and-Blues', 'Los Rojiazules'),
         ("The colours combine the red and blue of the city of Paris with the white of Saint-Germain-en-Laye, the royal town the club merged with at its founding.",
          "Los colores combinan el rojo y el azul de la ciudad de París con el blanco de Saint-Germain-en-Laye, la localidad real con la que el club se fusionó al fundarse."),
         ("France's dominant club and one of the youngest giants in Europe, founded in 1970 and built into a global brand in a single decade.",
          "El club dominante de Francia y uno de los gigantes más jóvenes de Europa, fundado en 1970 y convertido en marca global en una sola década."),
         'Parc des Princes',
         [("The two ends, Virage Auteuil and Virage Boulogne, have historically had very different cultures and their own songs.",
           "Las dos curvas, Virage Auteuil y Virage Boulogne, han tenido históricamente culturas muy distintas y sus propios cánticos."),
          ("The club motto is painted around the ground, so every visiting player reads it on the way out.",
           "El lema del club está pintado alrededor del estadio, así que todo jugador visitante lo lee al salir.")],
         ('Le Classique', 'Le Classique', 'Olympique de Marseille', 'Olympique de Marsella', 'culture-marseille',
          "Paris against Marseille: the capital and the port, and by far the biggest match in France.",
          "París contra Marsella: la capital y el puerto, y con diferencia el mayor partido de Francia."),
         ('ici-cest-paris', "Ici c'est Paris", "Ici c'est Paris",
          'On entering the stadium and after every goal', 'Al entrar al estadio y tras cada gol',
          '7fJc5ndphWD819fNpozomM', "Ici c'est Paris", 'fr', 'This is Paris', 'Esto es París',
          "Three words that work as a territorial warning: whatever you have elsewhere, here the city sets the terms. It is painted around the Parc des Princes and shouted back at every visiting support.",
          "Tres palabras que funcionan como advertencia territorial: tengas lo que tengas en otro sitio, aquí manda la ciudad. Está pintado alrededor del Parc des Princes y se le grita a cada afición visitante.")),

    card('culture-marseille', L1, 2, 'Olympique de Marseille',
         ('Marseille, France', 'Marsella, Francia'), 1899, ('White and sky blue', 'Blanco y azul cielo'),
         ('Les Olympiens', 'fr'), ('The Olympians', 'Los Olímpicos'),
         ("From the club's name, chosen in 1899 in tribute to the ancient Olympic ideal of amateur sport. Fans mostly just say 'OM'.",
          "Del nombre del club, elegido en 1899 en homenaje al ideal olímpico antiguo del deporte amateur. La afición suele decir simplemente 'OM'."),
         ("The only French club to have won the European Cup, and the one whose support is most often called the loudest in the country.",
          "El único club francés que ha ganado la Copa de Europa, y aquel cuya afición se considera más a menudo la más ruidosa del país."),
         'Stade Vélodrome',
         [("The club motto 'Droit au but' — 'straight to goal' — sits on the crest and is the oldest thing about the club.",
           "El lema del club, 'Droit au but' ('directo a portería'), está en el escudo y es lo más antiguo del club."),
          ("The Virage Nord and Virage Sud run organised ultra groups whose displays take weeks to prepare.",
           "El Virage Nord y el Virage Sud albergan grupos ultras organizados cuyas coreografías se preparan durante semanas.")],
         ('Le Classique', 'Le Classique', 'Paris Saint-Germain', None, 'culture-psg',
          "The south against the capital, in a fixture where the cultural gap matters as much as the table.",
          "El sur contra la capital, en un partido donde la distancia cultural importa tanto como la tabla."),
         ('allez-lom', "Allez l'OM", "Allez l'OM",
          'Throughout the match', 'Durante todo el partido',
          '2v4qTS1CAh9x37zwgm6sCO', "Allez l'OM", 'fr', 'Come on OM', 'Vamos, OM',
          "The simplest possible chant, and that is its strength: two words 60,000 people can hold for minutes at a time without anyone needing to know a verse.",
          "El cántico más simple posible, y ahí está su fuerza: dos palabras que 60.000 personas pueden sostener durante minutos sin que nadie necesite saberse una estrofa."),
         club_es='Olympique de Marsella'),
]

ARSENAL_CHANT = {
    'id': 'and-its-arsenal',
    'title': {'en': "And It's Arsenal", 'es': "And It's Arsenal"},
    'when': {'en': 'Rolling round the ground during play', 'es': 'Recorriendo el estadio durante el juego'},
    'sourceUrl': None,
    'spotifyUrl': sp('5yU1ncvZ5buQQXezr8tEJv'),
    'original': {'text': "And it's Arsenal!", 'lang': 'en'},
    'literal': {'en': "And it's Arsenal!", 'es': '¡Y es el Arsenal!'},
    'meaning': {
        'en': "A short refrain repeated until the whole ground is on it. English terrace songs often work like this: the words carry almost nothing, and the point is how many people are saying them at once.",
        'es': "Un estribillo corto que se repite hasta que todo el estadio lo canta. Los cánticos ingleses suelen funcionar así: la letra apenas dice nada y lo que importa es cuánta gente la canta a la vez.",
    },
}


def main():
    path = os.path.join(ROOT, 'league_feature', 'server', 'data', 'culture.json')
    cards = json.loads(io.open(path, encoding='utf-8').read())
    existing = {c['id'] for c in cards}

    added = [c for c in NEW if c['id'] not in existing]
    cards.extend(added)

    for c in cards:
        if c['id'] == 'culture-arsenal' and not any(ch['id'] == ARSENAL_CHANT['id'] for ch in c['chants']):
            c['chants'].append(ARSENAL_CHANT)

    io.open(path, 'w', encoding='utf-8').write(json.dumps(cards, ensure_ascii=False, indent=2) + '\n')
    print('added', len(added), 'cards; total', len(cards))
    print(Counter(c['leagueId'] for c in cards))


if __name__ == '__main__':
    main()
